package com.shepherd.shep_blog.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    BUSINESS_RULE_VIOLATION,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_JWT,
    CONFLICT,
    EXTERNAL_SERVICE_FAILURE,
    SHEP_BLOG_ERROR,
    INTERNAL_SERVER_ERROR
}
