PORT: 8080

DB_HOST: localhost
DB_PORT: 3306
DB_NAME: shep_blog
DB_USERNAME: root
DB_PASSWORD: 328436

HIKARI_MAXIMUM_POOL_SIZE: 5
HIKARI_MINIMUM_IDLE: 2
HIKARI_CONNECTION_TIMEOUT: 2000
HIKARI_IDLE_TIMEOUT: 600000
HIKARI_MAX_LIFETIME: 1800000

MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: osodavid001@gmail.com
MAIL_PASSWORD: nhlnstrfppyyxhsj
MAIL_FROM_EMAIL: noreply@shepblog.com
MAIL_FROM_NAME: ShepBlog

CORE_POOL_SIZE: 1
MAX_POOL_SIZE: 2
QUEUE_CAPACITY: 50

ADMIN_EMAIL: shepblog@yopmail.com
ADMIN_PASSWORD: Admin123$

CLIENT_URL: http://localhost:3000

RESET_PASSWORD_EXPIRATION: 900
EMAIL_CONFIRMATION_EXPIRATION: 900
ADMIN_INVITE_EXPIRATION: 1800
AUTHOR_ONBOARDING_EXPIRATION: 1800

JWT_SECRET_KEY: JXVsQRPwTtPf22oZUOjK0OYRaAZ5pkhULNZPubcxODmaOKfwurUocRVAuoPaU0tlT64rn7cBIzwCy1V5rALrOBCiXRCKlovZ3uihevWApC6NgMitTAtLjnG6co4cNAKnMbkhQk89h5QDZUzKbPGuQ0APm8LgVMFFhJ7RK8vBUC1k2x9xbr9C0wzu93zJFw4wDJMtQdIICwBFnf0Un9hqDPwzqd4vpAKh5k0TkhYkLKdAliVLmwCqfTI6sQzTDFLG8jdIYFCmDwaVF6QG6PxvtbaSlhFYcfpwB8b4KxNQ7B7s3dK2Ylb7aE8CF7d1GIQevkToTP1atzwamL3RQKRZzy74KqZT9tRXsE87OS3mzfezFzqDWm9GnsQtoqXfUVqqGDAtXNI89DgBLaJoCtxAb5tPzZwnGez6hFFTwhoESEDX6G9HnFyWruC6AmSeUGBrTGgAUiY0sXWWtglyN6hsj5T1e8kxXdAKbXFA7nVyEMl1O3GneVnSTKvHYhh3xOkq
JWT_EXPIRATION: 900
JWT_REFRESH_EXPIRATION: 86400
